matrix error?
C:\Users\roman\OneDrive\문서\GitHub\Spin_map_for_ParaView>python SkL_02_1016.py
C:\Users\roman\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = N.array(data, dtype=dtype, copy=copy)
Traceback (most recent call last):
  File "SkL_02_1016.py", line 100, in <module>
    S3=np.matrix([0.0],[[np.sin(phase3)],[-np.cos(phase3)]])
  File "C:\Users\roman\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\matrixlib\defmatrix.py", line 145, in __new__
    arr = N.array(data, dtype=dtype, copy=copy)
TypeError: Field elements must be 2- or 3-tuples, got '[matrix([[0.]])]'

怒られてる